eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/

sleuth:
  sampler:
    probability: 1.0

zipkin:
  base-url: http://zipkin.team-c.cloud.school.thoughtworks.cn

logging:
  level:
    org.springframework.web: DEBUG
